### ISSUE TITLE
with-class will not work when component returns a function

### ISSUE THREAD

**Issue by smogg** [RackSec/wilson#16]
for example - `sorted-table` returns fn, `with-class` will error

**Comment by lvh** [comment]
Hm, that's a good question!

I think it makes sense to keep the "only works on a hiccup data structure" behavior, but this is, um, interesting I guess :)

I wonder how that would work. If the input is a function, return `(fn [& args] (with-class cls (apply f args))` ?

**Comment by smogg** [comment]
That seems to kill component's reactivity. Another option would be to return a `form-3` component using `react/create-class` and add class using DOM api (for example, inside `:component-did-mount`). This might be a very ugly hack tho

**Comment by smogg** [comment]
Actually, scratch that - using `attr` on pseudo elements properly grabs attrs from parent. Problem solved

**Comment by smogg** [comment]
I believe this was fixed in #21
